---
- hosts: spine
  become: true
  user: cumulus
  gather_facts: false

  vars:
    spine01:
      asn: 42
      router_id: 192.168.0.201/32
      lo_ip: 192.168.0.201/32
      vrf_name: Tenant_Test
      vrf_vxlan_id: 42
    spine02:
      asn: 42
      router_id: 192.168.0.202/32
      lo_ip: 192.168.0.202/32
      vrf_name: Tenant_Test
      vrf_vxlan_id: 42
      
  roles:
    - /home/cumulus/ON-15/step-07/roles/interfaces
    - /home/cumulus/ON-15/step-07/roles/frr
    - /home/cumulus/ON-15/step-07/roles/hostname
