# startup.yaml

- hosts: switche
  name: if
  become: yes
  gather_facts: no
  tasks:
    - name: clean me up
      copy: 
        src: /home/cumulus/ON-15/step-cleanup/{{ inventory_hostname }}
        dest: /etc/nvue.d/startup.yaml
    # aktivieren
    - name: activate changes 
      shell: nv config apply startup -y
    # enalbe netd for 5.0 in case an older script was used before
    - name: netd enable
      shell: systemctl enable netd
    - name: netd start
      shell: systemctl start netd

# Host e/n/i Datei

- hosts: storage01:server11:server12:server13
  name: clean up interfaces
  become: yes
  gather_facts: no
  tasks:
    - name: Interfaces
      copy: 
        src: /home/cumulus/ON-15/compute
        dest: /etc/network/interfaces
    # aktivieren
    - name: activate changes on node
      shell: /sbin/ifreload -a
