# startup.yaml

- hosts: switche
  name: if
  become: yes
  gather_facts: no
  tasks:
    - name: clean me up
      copy: 
        src: /home/cumulus/ON-15/step-cleanup/{{ inventory_hostname }}
        dest: /etc/nvue.d/startup.yaml
    # aktivieren
    - name: activate changes 
      shell: nv config apply startup -y
    # enalbe netd for 5.0 in case an older script was used before
    - name: netd enable
      shell: systemctl enable netd
    - name: netd start
      shell: systemctl start netd

# comp issue 18-02-2022

- hosts: hypervisor01
  name: legacy bridge tool
  become: yes
  gather_facts: no
  tasks:
    - name: add brctl
      apt:
        name: brctl
        state: present

# Host e/n/i Datei

- hosts: storage01:server11:server12:server13:vm01:vm02:hypervisor01
  name: clean up interfaces
  become: yes
  gather_facts: no
  tasks:
    - name: Interfaces
      copy: 
        src: /home/cumulus/ON-15/step-cleanup/compute
        dest: /etc/network/interfaces
    # aktivieren
    - name: activate changes on node
      shell: /sbin/ifreload -a

- hosts: vm01:vm02
  name: clean up frr
  become: yes
  gather_facts: no
  tasks:
    - name: remove frr
      apt:
        name: frr
        state: absent

  tasks:
    - name: Remove daemons config
      ansible.builtin.file:
        path: /etc/frr/daemons
        state: absent
  
  tasks:
    - name: Remove frr config
      ansible.builtin.file:
        path: /etc/frr/frr.config
        state: absent
