- hosts: switche
  name: Configure /etc/frr/daemon
  become: yes
  gather_facts: false
  tasks:
    - copy:
        src: /home/cumulus/ON-15/step-01/daemons
        dest: /etc/frr/daemons
      notify:
        - frr_restart
        
  handlers:
    - name: frr_restart
      service:
        name=frr
        state=restarted
      listen: "frr_restart"
        
