- hosts: switche
  name: Configure /etc/frr/daemon
  become: yes
  gather_facts: false
  tasks:
    - copy:
        src: /home/cumulus/ON-15/step-01/daemons
        dest: /etc/frr/daemons
    - shell: systemctl restart frr
        
- hosts: vm
  name: Configure /etc/frr/host-daemon
  become: yes
  gather_facts: false
  tasks:
    - copy:
        src: /home/cumulus/ON-15/step-01/host-daemons
        dest: /etc/frr/daemons
    - shell: systemctl restart frr
        
