- hosts: vm
  name: Install frr
  become: yes
  gather_facts: no
  tasks:
    - name: Add frr repo key
      ansible.builtin.apt_key:
        url: https://deb.frrouting.org/frr/keys.asc
        state: present

    - name: Add frr repo
      shell: sudo echo deb https://deb.frrouting.org/frr bionic frr-stable | sudo tee -a /etc/apt/sources.list.d/frr.list

    - name: Install frr
      apt:
        pkg:
        - frr
        - frr-pythontools
        
    - name: kick frr
      shell: systemctl restart frr


