- hosts: hypervisor01
  name: create vSwitch1 and vSwitch2
  become: yes
  gather_facts: fasle
  task:
    - copy:
        src: /home/cumulus/ON-15/step-01/hypervisor01
        dest: /home/cumulus/hypervisor01
        mode: u+xrw
    - shell: ./hypervisor01

- hosts: switche
  name: Configure /etc/frr/daemon
  become: yes
  gather_facts: false
  tasks:
    - copy:
        src: /home/cumulus/ON-15/step-01/daemons
        dest: /etc/frr/daemons
    - shell: systemctl restart frr
        
- hosts: vm
  name: Configure /etc/frr/host-daemon
  become: yes
  gather_facts: false
  tasks:
    - copy:
        src: /home/cumulus/ON-15/step-01/host-daemons
        dest: /etc/frr/daemons
    - shell: systemctl restart frr
        
- hosts: vm
  name: Install frr
  become: yes
  gather_facts: no
  tasks:
    - name: Add frr repo key
      ansible.builtin.apt_key:
        url: https://deb.frrouting.org/frr/keys.asc
        state: present

    - name: Add frr repo
      shell: sudo echo deb https://deb.frrouting.org/frr bionic frr-stable | sudo tee -a /etc/apt/sources.list.d/frr.list
      
    - name: update chache
      apt: 
        name: frr
        update_cache: yes

    - name: Install frr
      apt:
        pkg:
        - frr
        - frr-pythontools
        
    - name: kick frr
      shell: systemctl restart frr

- hosts: switche
  name: disable NCLU and enable NVUE
  become: yes
  gather_facts: no
  tasks:
    - name: stop NCLU
      shell: systemctl stop netd
    - name: disable NCLU
      shell: systemctl disable netd
    - name: enable NVUE was CUE
      shell: systemctl enable nvued
    - name: start NVUE was CUE
      shell: systemctl start nvued   
