---
- name: restart frr
  service:
    name: frr
    state: restarted
- name: reload frr
  service:
    name: frr
    state: reloaded
- name: enable frr
  service:
    name: frr
    state: started
    enabled: true
