---
- hosts: vm
  name: NOT RECOMMENDED ***** diabling OCSP verification ***** NOT RECOMMENDED
  become: yes
  gather_facts: false
  tasks: 
    - name: copy apt config file
      copy:
        dest: /etc/apt/apt.conf.d/99verify-peer.conf
        content: |
          Acquire { https::Verify-Peer false }
          
- hosts: vm
  name: Install frr
  become: yes
  gather_facts: false
  tasks:
    - name: Add frr repo key
      ansible.builtin.apt_key:
        url: https://deb.frrouting.org/frr/keys.asc
        state: present

    - name: Add frr repo
      shell: sudo echo deb https://deb.frrouting.org/frr bionic frr-stable | sudo tee -a /etc/apt/sources.list.d/frr.list

    - name: update cache
      apt:
        name: frr
        update_cache: yes

    - name: Install frr
      apt:
        pkg:
        - ca-certificates
        - frr
        - frr-pythontools

    - name: kick frr
      shell: systemctl restart frr
      
- hosts: vm
  name: Configure /etc/frr/daemon
  become: yes
  gather_facts: false
  tasks:
    - copy:
        src: /home/cumulus/ON-15/inventory/files/hdaemons
        dest: /etc/frr/daemons
    - shell: systemctl restart frr
